CC= 	gcc
COMPILE=	$(CC)-c -std=c99 
LINK=	$(CC) -o
REMOVE=rm -f
PATH=/home/jake/PHYS_115/Homework1/

#1a
homework1a : $(PATH)homework1a.o
	$(LINK) homework1a homework1a.o

homework1a.o : $(PATH)homeowork1a.c
	$(COMPILE) homework1a.c

